### ISSUE TITLE
Feature request: option to show out-of-scope domains

### ISSUE THREAD

**Issue by Zarcolio** [serain/bbrecon#2]
Hi Serain,

I would like to see an option to get out-of-scope domains.
That could come in handy when checking what is allowed and what is not, for example with:
`subfinder -d example.com|grep -xvf exclusions.txt`
Also, for my Google dork script Sitedorks out-of-scope domains could come in handy when looking for information about a certain company.
Is it an option for you to add this option?

Grtz,
Zarcolio

**Comment by serain** [comment]
Hey @Zarcolio 

You can get the program as JSON and from there get the out-of-scopes web domains with something like:

```
$ bbrecon get programs segment -o json | jq '.[].out_scope[] | select(.type | contains("web")) | .value'
```

Note that you can also get the domains directly from bbrecon with:

```
$ bbrecon get domains segment
```

bbrecon currently fetches all domains in scope from the following sources, more than once a day, and automatically excludes out-of-scope domains:
* bufferover
* rapiddns
* crt.sh
* sublist3r api

**Comment by Zarcolio** [comment]
Awesome! I'll have a go at it tomorrow 😁
Thx for the info.
Grtz

**Comment by Zarcolio** [comment]
Looks like what I wanted, thx!
