### ISSUE TITLE
console.bugbountyrecon.com not working with firefox

### ISSUE THREAD

**Issue by sudoaza** [serain/bbrecon#6]
Can login but get no token, the console shows this error
TypeError: this.user.wc is undefined

**Comment by serain** [comment]
Thanks. I'm looking into it.

**Comment by serain** [comment]
@sudoaza I've issued a temporary fix. Can you let me know if it works for you?

**Comment by sudoaza** [comment]
works thanks. For what is worth i had already forwarded the google token to the api and got it working that way :D
