### ISSUE TITLE
Unable to obtain an api key.

### ISSUE THREAD

**Issue by Ra-yy** [serain/bbrecon#9]
Hey there,
I signed up for you service using the google sso and reached the page which allows you to copy the api_key, But for some weird reason, the api key field is blank. Clicking on the copy button doesn't work either.

Is there some issue going on with the site right now?

**Comment by serain** [comment]
Hi @Ra-yy , thanks for flagging. I'm looking into this.

**Comment by serain** [comment]
Fixed, thanks for flagging.

Can you check on your end and confirm?

 Should work for now and I'll need to make a long term fix.

**Comment by Ra-yy** [comment]
Yes the issue seems fixed now, was able to obtain an api key. Thank you for looking into this!
